package com.cs428.pandemic.frontEnd;

/**
 * Created by Chad Bacon on 2/16/2016.
 *
 * This interface will be used by any role-exclusive action objects generated by the model. When
 * passed to the UI the UI will simply pass it a popup dialog which the command object will
 * use to query the user for necessary data. The command object will then execute the command by
 * making calls to the model.
 */
public interface ICommandObject {
    void doCommand(/*TODO: determine param type*/);
}
